# Generated by Django 6.0.2 on 2026-02-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
