# Generated by Django 6.0.2 on 2026-02-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_app', '0002_alter_transacao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='type',
            field=models.CharField(blank=True, choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, null=True),
        ),
    ]
