# Generated by Django 6.0.2 on 2026-03-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_app', '0003_transacao_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='type',
            field=models.CharField(blank=True, choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('+poupanca', '+ Poupanca'), ('-poupanca', '- Poupanca')], max_length=10, null=True),
        ),
    ]
