# Generated by Django 6.0.2 on 2026-03-05 16:52

import autenticacao_app.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membro da Equipe')),
                ('avatar', models.ImageField(blank=True, help_text='Imagem de Perfil', null=True, upload_to='uploads/avatars', verbose_name='Imagem de Perfil')),
                ('tema', models.CharField(choices=[('light', 'light'), ('dark', 'dark'), ('cupcake', 'cupcake'), ('bumblebee', 'bumblebee'), ('emerald', 'emerald'), ('corporate', 'corporate'), ('synthwave', 'synthwave'), ('retro', 'retro'), ('cyberpunk', 'cyberpunk'), ('valentine', 'valentine'), ('halloween', 'halloween'), ('garden', 'garden'), ('forest', 'forest'), ('aqua', 'aqua'), ('lofi', 'lofi'), ('pastel', 'pastel'), ('fantasy', 'fantasy'), ('wireframe', 'wireframe'), ('black', 'black'), ('luxury', 'luxury'), ('dracula', 'dracula'), ('cmyk', 'cmyk'), ('autumn', 'autumn'), ('business', 'business'), ('acid', 'acid'), ('lemonade', 'lemonade'), ('night', 'night'), ('coffee', 'coffee'), ('winter', 'winter'), ('dim', 'dim'), ('nord', 'nord'), ('sunset', 'sunset')], default='night', max_length=100, verbose_name='Tema')),
                ('fisioterapeuta', models.BooleanField(default=False, verbose_name='Fisioterapeuta')),
                ('receber_notificacao_aniversario', models.BooleanField(default=False, verbose_name='Receber Notificações de Aniversariantes?')),
                ('cor', models.CharField(default='#383669', max_length=100, null=True, verbose_name='Cor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', autenticacao_app.models.UsuarioManager()),
            ],
        ),
    ]
